FROM kalilinux/kali-rolling:arm64@sha256:69a5b325c604a86d5dac0992056fdeac6c8357972451517dc3fdc779f00ffbe9

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2025.1.4
