FROM kalilinux/kali-rolling:i386@sha256:3fc1384b84456529003ba3beec79e30737bb764acc5dcd337e3e3c3167bfc211

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2025.1.3

