FROM kalilinux/kali-rolling:armel@sha256:ce2a6ad15241c3578cded88c428e4ba55a7c99ec8775e20967ec722d26d46c35

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2025.1.4
