FROM kalilinux/kali-rolling:arm64@sha256:26e61b1b149ced2f5898e109ddff2cdfd93ca6e7d1438b81e5c83ca97ed90018

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2025.1.3
