FROM kalilinux/kali-rolling:armel@sha256:b1609932fe6d612815211ebbb04bb47e79ddb9b17e8ef6f4f61dd9934c15eaee

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2025.1.3
