name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  add-rebase-merge-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and add label
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const title = context.payload.pull_request.title;
            const regex = new RegExp(/^\w+\(\*\): .+/);
            
            if (regex.test(title)) {
              const labels = context.payload.pull_request.labels.map(label => label.name);
              if (!labels.includes('rebase-merge :m:')) {
                await github.rest.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['rebase-merge :m:']
                });
                console.log('Added rebase-merge :m: label as PR title contains (*) pattern');
              }
            }
